version: '3'

services: 

  laravel:
    build: 
      context: ./laravel
      dockerfile: Dockerfile.prod
    image: jefjrfigueiredo/laravel:prod
    container_name: laravel
    networks: 
      - laranet
    volumes: 
      - ./laravel:/var/www/laravel

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: jefjrfigueiredo/nginx:prod
    container_name: nginx
    networks: 
      - laranet
    ports: 
      - "8080:80"
    volumes: 
      - ./nginx:/usr/src/app/nginx

  db:
    image: mysql:8.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - laranet

networks: 
  laranet:
    driver: bridge      